Added types first letter is in upper case
htmlacademy-ecmascript/1541333-big-trip-15 pull request #11
Opened 2021-08-23 09:42 UTC by sanich123

2021-08-24 07:13 UTC, ArtMan-8 requested changes

2021-08-24 07:13 UTC, ArtMan-8 commented on src/utils/rendering-data-utils.js
> +    <input class="event__offer-checkbox  visually-hidden" id="event-offer-luggage-${index}" type="checkbox" name="event-offer-luggage">
Индекс не подойдёт, нужен айдишник события.
К индексам массивов вообще никак не стоит привязываться, эта не надёжная штука.

2021-08-24 07:13 UTC, ArtMan-8 commented on src/utils/rendering-data-utils.js
> +          <label class="event__type-label  event__type-label--${type}" for="event-type-${type}-${id}">${type[0].toUpperCase() + type.split('').splice(1).join('')}</label>
`type[0].toUpperCase() + type.split('').splice(1).join('')`
Такие штуки лучше выносить в функция, и прятать за понятным названием.
Читабельность будет лучше + переиспользуемость кода (DRY)

2021-08-24 07:13 UTC, ArtMan-8 commented on src/utils/rendering-data-utils.js
> +export const sortList = (sortTypes, currentSortType) => sortTypes.map((sortType) =>
Структуры не поправлял?
Можем пока оставить, но перед защитой будем причёсывать.

2021-08-24 09:16 UTC, sanich123 commented on package.json
> +    "nanoid": "3.1.22",
Если бы еще кто-нибудь объяснил, как установить в обычные зависимости, а не в дев. Я правильно понимаю, что при утсановке флага -DE это в дев зависимости, а если просто -E то в обычные? Просто это никто не объяснял, реально. Это правильное предположение?

2021-08-24 09:36 UTC, sanich123 commented on src/utils/rendering-data-utils.js
> +    <input class="event__offer-checkbox  visually-hidden" id="event-offer-luggage-${index}" type="checkbox" name="event-offer-luggage">
Переделал на уникальный айдишник

2021-08-24 09:38 UTC, ArtMan-8 commented on package.json
> +    "nanoid": "3.1.22",
Верно,
должны были на первых лекциях

2021-08-24 09:40 UTC, sanich123 commented on src/utils/rendering-data-utils.js
> +          <label class="event__type-label  event__type-label--${type}" for="event-type-${type}-${id}">${type[0].toUpperCase() + type.split('').splice(1).join('')}</label>
Поправил

2021-08-24 09:43 UTC, sanich123 commented on package.json
> +    "nanoid": "3.1.22",
Ничего подобного не объясняли, честно

2021-08-25 07:00 UTC, ArtMan-8 approved these changes

2021-08-25 07:12 UTC, ArtMan-8 approved these changes

2021-08-25 07:12 UTC, merged