some fixings
htmlacademy-ecmascript/1541333-big-trip-15 pull request #4
Opened 2021-07-28 11:25 UTC by sanich123

2021-08-04 12:15 UTC, ArtMan-8 commented on src/main.js
> +const NUMBER_COPIES = 15;
Что за номера, что за копии?
Мы же точно знаем что это - количество точек маршрута - `POINT_COUNT`

2021-08-04 12:44 UTC, ArtMan-8 requested changes

2021-08-04 12:44 UTC, ArtMan-8 commented on src/main.js
> +for (let i = 0; i < NUMBER_COPIES; i++) {
Используем `for of` или `forEach`, если проходимся по всем элементам коллекции `for` не используем.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/main.js
> +render(priceAndTripSection, priceAndTrip(points), renderPosition.AFTERBEGIN);
`AFTERBEGIN` повторяется гораздо чаще чем `BEFOREEND`, можно сделать параметр по умолчанию.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/main.js
> +export { points };
Точка входа не должна ничего экспортировать.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/mock/createData.js
> +const pictures = [
А чего не генерируешь массив случайной длины?

2021-08-04 12:44 UTC, ArtMan-8 commented on src/utils/utils.js
> +export const humanizeDate = (date, format) => {
Если промежуточные данные не используются, лучше сразу делать возврат
`export const humanizeDate = (date, format) => dayjs(date).format(format)`

И функция ниже тоже самое.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/mock/createData.js
> +const types = ['taxi',
`types`, `cities`, `options`, `descriptions` - константы.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/view/editingPoint.js
> +export const editPoint = (points = {}) => {
Можно сразу деструктировать в параметрах, и передавать значения по умолчанию.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/view/editingPoint.js
> +    dateFrom = '31/12/1999 23:59',
Даты по умолчанию можно передавать текущие.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/view/editingPoint.js
> +    `      <div class="event__offer-selector">
Лишние пробелы после бэктика.

2021-08-04 12:44 UTC, ArtMan-8 commented on src/view/pointsList.js
> +  const duration = () => {
Не явное использование функции, нужно явно передавать параметры.

2021-08-05 06:22 UTC, sanich123 commented on src/main.js
> +for (let i = 0; i < NUMBER_COPIES; i++) {
Исправил на forEach

2021-08-05 06:24 UTC, sanich123 commented on src/main.js
> +render(priceAndTripSection, priceAndTrip(points), renderPosition.AFTERBEGIN);
5 BEFORE, 7 AFTERBEGIN, оставлю пока, как есть, количество почти одинаковое

2021-08-05 06:24 UTC, sanich123 commented on src/main.js
> +export { points };
Исправил

2021-08-05 06:27 UTC, sanich123 commented on src/mock/createData.js
> +const pictures = [
Массив случайной длины генерирую в другой функции, getRandomArrayLength, а getRandomArrayMember я использую для получения отдельного случайного элемента массива

2021-08-05 06:30 UTC, sanich123 commented on src/utils/utils.js
> +export const humanizeDate = (date, format) => {
Исправил!

2021-08-05 06:31 UTC, sanich123 commented on src/view/editingPoint.js
> +    `      <div class="event__offer-selector">
Исправил

2021-08-05 06:34 UTC, sanich123 commented on src/view/pointsList.js
> +    if (millisecs < 3600000) {
Исправил!

2021-08-05 06:41 UTC, sanich123 commented on src/view/pointsList.js
> +  const duration = () => {
Исправил

2021-08-05 08:11 UTC, ArtMan-8 commented on src/mock/createData.js
> +const pictures = [
Имею ввиду, что бы количество рисунков было случайным у каждой точки.

2021-08-05 08:46 UTC, sanich123 commented on src/mock/createData.js
> +const pictures = [
const generateDestination = () => ({
  description: getRandomArrayLengthByNumber(0, DESCRIPTIONS, 5),
  name: getRandomArrayMember(CITIES),
  pictures: getRandomArrayLength(1, PICTURES),
});
Вот так вот работает, вроде как надо

2021-08-05 09:07 UTC, ArtMan-8 commented on src/mock/createData.js
> +const pictures = [
И тут у нас заметна проблема с неймингом
`pictures: getRandomArrayLength(1, PICTURES)`
Речь про `pictures`, а судя из названии функция получаем случайную длину массива.
Так же и другие функции.
Массива чего, и разве длину получаем.
На такие моменты обращай внимание, это важно для понятности кода.
Особенно когда он разрастается.

2021-08-05 11:12 UTC, ArtMan-8 approved these changes

2021-08-05 11:12 UTC, ArtMan-8 commented on src/mock/createData.js
> +const getOffersByType = (arr, tip) => {
Пометь себе 'на подумать', как то очень криво.
В иделаи никаких циклов быть не должно, должны получать нужные офферы просто по ключу.

2021-08-05 11:12 UTC, ArtMan-8 commented on src/utils/utils.js
> +export const currentTime = dayjs().format('DD/MM/YY HH:mm');
Почему не функция?
Так мы раз значение вычислили и сохранили.
А нам при каждом вызове нужна текущая дата.

2021-08-05 11:12 UTC, ArtMan-8 commented on src/view/pointsList.js
> +  const duration = (begin, end) => {
Все вспомогательные функции и константы выносим из функции генерации разметки.

2021-08-05 11:12 UTC, ArtMan-8 approved these changes

2021-08-05 11:13 UTC, merged

2021-08-05 11:19 UTC, sanich123 commented on src/mock/createData.js
> +const getOffersByType = (arr, tip) => {
Я исходил из вот этой структуры по ТЗ, тут (по-моему) без цикла не обойтись. Offer:
{
  "type": "taxi",
  "offers": [
    {
      "title": "Upgrade to a business class",
      "price": 120
    }, {
      "title": "Choose the radio station",
      "price": 60
    }
  ]
}