Module5 task2
htmlacademy-ecmascript/1541333-big-trip-15 pull request #9
Opened 2021-08-16 08:03 UTC by sanich123

2021-08-17 15:38 UTC, sanich123 commented
Сортировка работает, но есть несколько проблем.
1. Странно рендерится изначальный список, он отсортирован по возрастанию даты, но выводится наоборот, хотя я нигде его больше не сортировал, кроме как в main.
2. Непонятно, как сделать, чтобы у выбираемых тегов сортировки переносился атрибут checked.
3. При сортировке и при нажатии на звездочку формируется пустой li, или же 15 пустых li в случае с сортировкой.

2021-08-18 14:52 UTC, ArtMan-8 requested changes

2021-08-18 14:52 UTC, ArtMan-8 commented on src/presenter/trip-list.js
>      this._renderEmpty(points);
Сигнатура функции не принимает аргументов, а здесь передаём.

2021-08-18 14:52 UTC, ArtMan-8 commented on src/presenter/trip-list.js
> +  _renderEmpty() {
Название метода вводит в заблуждение.
Может стоит разбить на два метода?

А во время инициализации проверять, что рисовать.

2021-08-18 14:52 UTC, ArtMan-8 commented on src/view/sort.js
>  <div class="trip-sort__item  trip-sort__item--day">
Где генерация типа сортировок?
Обрати внимание, что некоторые из них `disabled`.
Если их 100500 будет, будешь каждую руками писать.

2021-08-18 20:15 UTC, sanich123 commented on src/presenter/trip-list.js
>      this._renderEmpty(points);
Поправил

2021-08-18 20:20 UTC, sanich123 commented on src/presenter/trip-list.js
> +  _renderEmpty() {
Пока не понял, про что ты. Если про метод renderEmpty - то он по-моему понятный, загрузка пустой страницы, если нет точек. Если handleModeChange - тоже вроед понятненькго

2021-08-19 12:55 UTC, sanich123 commented on src/view/sort.js
>  <div class="trip-sort__item  trip-sort__item--day">
Я написал фукнцию по генерации, но не понимаю, как сделать, чтобы первый элемент по умолчанию был checked. Раньше это достигалось тупо тем, что в разметке у первого элемента был checked. А теперь почему-то при загрузке страницы checked становится offers, которые не должны точно им быть. После загрузки все работает вроде нормально, но почему это не работает, и как это исправить - не понимаю

2021-08-20 17:34 UTC, ArtMan-8 approved these changes

2021-08-20 17:34 UTC, ArtMan-8 commented on src/utils/common.js
> +  day: 'day',
В перечислении ключи в верхнем регистре.

2021-08-20 17:34 UTC, ArtMan-8 commented on src/presenter/trip-point.js
> +  init(point, index) {
Зачем индекс передаёшь?
При добавлении новых точек индексы съедут.
В самой точке есть id, и уже в форме нужно его использовать.

Здесь и в других местах.

2021-08-20 17:34 UTC, merged

2021-08-21 08:42 UTC, sanich123 commented on src/presenter/trip-point.js
> +  init(point, index) {
Думал, что id нельзя. Передал в форму id из точки.

2021-08-21 09:34 UTC, ArtMan-8 commented on src/presenter/trip-point.js
> +  init(point, index) {
Для этого оно и есть,
по-моему я упоминал об этом.